// libs/sdk/src/react/stream.custom.tsx
/* __LC_ALLOW_ENTRYPOINT_SIDE_EFFECTS__ */

"use client";

import {
  useEffect,
  useCallback,
  useMemo,
  useRef,
  useState,
  useSyncExternalStore,
} from "react";
import { EventStreamEvent, StreamManager } from "../ui/manager.js";
import type {
  GetUpdateType,
  GetCustomEventType,
  GetInterruptType,
  GetToolCallsType,
  GetConfigurableType,
  UseStreamTransport,
  AnyStreamCustomOptions,
  CustomSubmitOptions,
} from "../ui/types.js";
import type { UseStreamCustom } from "./types.js";
import { type Message } from "../types.messages.js";
import { getToolCallsWithResults } from "../utils/tools.js";
import { MessageTupleManager } from "../ui/messages.js";
import { Interrupt } from "../schema.js";
import { BytesLineDecoder, SSEDecoder } from "../utils/sse.js";
import { IterableReadableStream } from "../utils/stream.js";
import { useControllableThreadId } from "./thread.js";
import { Command } from "../types.js";
import type { BagTemplate } from "../types.template.js";
import {
  isBrowserToolInterrupt,
  handleBrowserToolInterrupt,
} from "../browser-tools.js";

interface FetchStreamTransportOptions {
  /**
   * The URL of the API to use.
   */
  apiUrl: string;

  /**
   * Default headers to send with requests.
   */
  defaultHeaders?: HeadersInit;

  /**
   * Specify a custom fetch implementation.
   */
  fetch?: typeof fetch | ((...args: any[]) => any); // eslint-disable-line @typescript-eslint/no-explicit-any

  /**
   * Callback that is called before the request is made.
   */
  onRequest?: (
    url: string,
    init: RequestInit
  ) => Promise<RequestInit> | RequestInit;
}

export class FetchStreamTransport<
  StateType extends Record<string, unknown> = Record<string, unknown>,
  Bag extends BagTemplate = BagTemplate
> implements UseStreamTransport<StateType, Bag>
{
  constructor(private readonly options: FetchStreamTransportOptions) {}

  async stream(payload: {
    input: GetUpdateType<Bag, StateType> | null | undefined;
    context: GetConfigurableType<Bag> | undefined;
    command: Command | undefined;
    signal: AbortSignal;
  }): Promise<AsyncGenerator<{ id?: string; event: string; data: unknown }>> {
    const { signal, ...body } = payload;

    let requestInit: RequestInit = {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...this.options.defaultHeaders,
      },
      body: JSON.stringify(body),
      signal,
    };

    if (this.options.onRequest) {
      requestInit = await this.options.onRequest(
        this.options.apiUrl,
        requestInit
      );
    }
    const fetchFn = this.options.fetch ?? fetch;

    const response = await fetchFn(this.options.apiUrl, requestInit);
    if (!response.ok) {
      throw new Error(`Failed to stream: ${response.statusText}`);
    }

    const stream = (
      response.body || new ReadableStream({ start: (ctrl) => ctrl.close() })
    )
      .pipeThrough(BytesLineDecoder())
      .pipeThrough(SSEDecoder());

    return IterableReadableStream.fromReadableStream(stream);
  }
}

export function useStreamCustom<
  StateType extends Record<string, unknown> = Record<string, unknown>,
  Bag extends BagTemplate = BagTemplate
>(
  options: AnyStreamCustomOptions<StateType, Bag>
): UseStreamCustom<StateType, Bag> {
  type UpdateType = GetUpdateType<Bag, StateType>;
  type CustomType = GetCustomEventType<Bag>;
  type InterruptType = GetInterruptType<Bag>;
  type ConfigurableType = GetConfigurableType<Bag>;
  type ToolCallType = GetToolCallsType<StateType>;

  const [messageManager] = useState(() => new MessageTupleManager());
  const [stream] = useState(
    () =>
      new StreamManager<StateType, Bag>(messageManager, {
        throttle: options.throttle ?? false,
        subagentToolNames: options.subagentToolNames,
        filterSubagentMessages: options.filterSubagentMessages,
      })
  );

  useSyncExternalStore(
    stream.subscribe,
    stream.getSnapshot,
    stream.getSnapshot
  );

  const [threadId, onThreadId] = useControllableThreadId(options);
  const threadIdRef = useRef<string | null>(threadId);

  // Cancel the stream if thread ID has changed
  useEffect(() => {
    if (threadIdRef.current !== threadId) {
      threadIdRef.current = threadId;
      stream.clear();
    }
  }, [threadId, stream]);

  const getMessages = useCallback(
    (value: StateType): Message[] => {
      const messagesKey = options.messagesKey ?? "messages";
      return Array.isArray(value[messagesKey])
        ? (value[messagesKey] as Message[])
        : [];
    },
    [options.messagesKey]
  );

  const setMessages = useCallback(
    (current: StateType, messages: Message[]): StateType => {
      const messagesKey = options.messagesKey ?? "messages";
      return { ...current, [messagesKey]: messages };
    },
    [options.messagesKey]
  );

  const historyValues = useMemo(() => {
    return options.initialValues ?? ({} as StateType);
  }, [options.initialValues]);

  // Reconstruct subagents from initialValues when:
  // 1. Subagent filtering is enabled
  // 2. Not currently streaming
  // 3. initialValues has messages
  // This ensures subagent visualization works with cached/persisted state
  const historyMessages = getMessages(historyValues);
  const shouldReconstructSubagents =
    options.filterSubagentMessages &&
    !stream.isLoading &&
    historyMessages.length > 0;

  useEffect(() => {
    if (shouldReconstructSubagents) {
      // skipIfPopulated: true ensures we don't overwrite subagents from active streaming
      stream.reconstructSubagents(historyMessages, { skipIfPopulated: true });
    }
    // We intentionally only run this when shouldReconstructSubagents changes
    // to avoid unnecessary reconstructions during streaming
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [shouldReconstructSubagents, historyMessages.length]);

  const stop = () => stream.stop(historyValues, { onStop: options.onStop });

  const submit = useCallback(
    async (
      values: UpdateType | null | undefined,
      submitOptions?: CustomSubmitOptions<StateType, ConfigurableType>
    ) => {
      let usableThreadId = threadId;

      stream.setStreamValues(() => {
        if (submitOptions?.optimisticValues != null) {
          return {
            ...historyValues,
            ...(typeof submitOptions.optimisticValues === "function"
              ? submitOptions.optimisticValues(historyValues)
              : submitOptions.optimisticValues),
          };
        }

        return { ...historyValues };
      });

      await stream.start(
        async (signal: AbortSignal) => {
          if (!usableThreadId) {
            // generate random thread id
            usableThreadId = crypto.randomUUID();
            threadIdRef.current = usableThreadId;
            onThreadId(usableThreadId);
          }

          if (!usableThreadId) {
            throw new Error("Failed to obtain valid thread ID.");
          }

          return options.transport.stream({
            input: values,
            context: submitOptions?.context,
            command: submitOptions?.command,
            signal,
            config: {
              ...submitOptions?.config,
              configurable: {
                thread_id: usableThreadId,
                ...submitOptions?.config?.configurable,
              } as unknown as GetConfigurableType<Bag>,
            },
          }) as Promise<
            AsyncGenerator<EventStreamEvent<StateType, UpdateType, CustomType>>
          >;
        },
        {
          getMessages,
          setMessages,

          initialValues: {} as StateType,
          callbacks: options,

          onSuccess: () => undefined,
          onError(error) {
            options.onError?.(error, undefined);
          },
        }
      );
    },
    [
      threadId,
      stream,
      getMessages,
      setMessages,
      options,
      historyValues,
      onThreadId,
    ]
  );

  // Browser tools handling
  const browserToolsRef = useRef(options.browserTools);
  browserToolsRef.current = options.browserTools;

  const onBrowserToolRef = useRef(options.onBrowserTool);
  onBrowserToolRef.current = options.onBrowserTool;

  // Track which browser tool interrupts have been handled to prevent duplicates
  const handledBrowserToolsRef = useRef<Set<string>>(new Set());

  // Reset handled browser tools when thread changes
  useEffect(() => {
    handledBrowserToolsRef.current.clear();
  }, [threadId]);

  // Handle browser tool interrupts
  useEffect(() => {
    const browserTools = browserToolsRef.current;
    if (!browserTools?.length) return;
    if (!stream.values) return;

    // Check for browser tool interrupt in values
    const interrupts = stream.values.__interrupt__;
    if (!Array.isArray(interrupts) || interrupts.length === 0) return;

    // Find browser tool interrupts that haven't been handled
    for (const interrupt of interrupts) {
      if (!isBrowserToolInterrupt(interrupt.value)) continue;

      const interruptId = interrupt.id ?? interrupt.value.toolCall.id ?? "";
      if (handledBrowserToolsRef.current.has(interruptId)) continue;

      // Mark as handled before async operation
      handledBrowserToolsRef.current.add(interruptId);

      // Handle the browser tool interrupt
      void handleBrowserToolInterrupt(
        interrupt.value,
        browserTools,
        onBrowserToolRef.current
      ).then((result) => {
        // Resume with the tool result
        void submit(null, {
          command: {
            resume: result.toolCallId
              ? { [result.toolCallId]: result.value }
              : result.value,
          },
        });
      });
    }
  }, [stream.values, submit]);

  return {
    get values() {
      return stream.values ?? ({} as StateType);
    },

    error: stream.error,
    isLoading: stream.isLoading,

    stop,
    submit,

    get interrupts(): Interrupt<InterruptType>[] {
      if (
        stream.values != null &&
        "__interrupt__" in stream.values &&
        Array.isArray(stream.values.__interrupt__)
      ) {
        const valueInterrupts = stream.values.__interrupt__;
        if (valueInterrupts.length === 0) return [{ when: "breakpoint" }];
        return valueInterrupts;
      }

      return [];
    },

    get interrupt(): Interrupt<InterruptType> | undefined {
      const all = this.interrupts;
      if (all.length === 0) return undefined;
      if (all.length === 1) return all[0];

      // Multiple interrupts: return the array for backward compat
      return all as Interrupt<InterruptType>;
    },

    get messages(): Message<ToolCallType>[] {
      if (!stream.values) return [];
      return getMessages(stream.values);
    },

    get toolCalls() {
      if (!stream.values) return [];
      const msgs = getMessages(stream.values);
      return getToolCallsWithResults<ToolCallType>(msgs);
    },

    getToolCalls(message) {
      if (!stream.values) return [];
      const msgs = getMessages(stream.values);
      const allToolCalls = getToolCallsWithResults<ToolCallType>(msgs);
      return allToolCalls.filter((tc) => tc.aiMessage.id === message.id);
    },

    get subagents() {
      return stream.getSubagents();
    },

    get activeSubagents() {
      return stream.getActiveSubagents();
    },

    getSubagent(toolCallId: string) {
      return stream.getSubagent(toolCallId);
    },

    getSubagentsByType(type: string) {
      return stream.getSubagentsByType(type);
    },

    getSubagentsByMessage(messageId: string) {
      return stream.getSubagentsByMessage(messageId);
    },
  };
}

// libs/sdk-angular/src/stream.custom.ts
import { signal, computed, effect } from "@angular/core";
import {
  StreamManager,
  MessageTupleManager,
  extractInterrupts,
  toMessageClass,
  ensureMessageInstances,
  type EventStreamEvent,
  type GetUpdateType,
  type GetCustomEventType,
  type GetInterruptType,
  type GetConfigurableType,
  type GetToolCallsType,
  type AnyStreamCustomOptions,
  type CustomSubmitOptions,
  type MessageMetadata,
} from "@langchain/langgraph-sdk/ui";
import { getToolCallsWithResults } from "@langchain/langgraph-sdk/utils";
import type { BagTemplate, Message, Interrupt } from "@langchain/langgraph-sdk";
import {
  isBrowserToolInterrupt,
  handleBrowserToolInterrupt,
} from "@langchain/langgraph-sdk";

export function useStreamCustom<
  StateType extends Record<string, unknown> = Record<string, unknown>,
  Bag extends BagTemplate = BagTemplate,
>(options: AnyStreamCustomOptions<StateType, Bag>) {
  type UpdateType = GetUpdateType<Bag, StateType>;
  type CustomType = GetCustomEventType<Bag>;
  type InterruptType = GetInterruptType<Bag>;
  type ConfigurableType = GetConfigurableType<Bag>;
  type ToolCallType = GetToolCallsType<StateType>;

  const messageManager = new MessageTupleManager();
  const stream = new StreamManager<StateType, Bag>(messageManager, {
    throttle: options.throttle ?? false,
    subagentToolNames: options.subagentToolNames,
    filterSubagentMessages: options.filterSubagentMessages,
    toMessage: toMessageClass,
  });

  const streamValues = signal<StateType | null>(stream.values);
  const streamError = signal<unknown>(stream.error);
  const isLoading = signal(stream.isLoading);

  const subagentVersion = signal(0);

  effect((onCleanup) => {
    const unsubscribe = stream.subscribe(() => {
      streamValues.set(stream.values);
      streamError.set(stream.error);
      isLoading.set(stream.isLoading);
      subagentVersion.update((v) => v + 1);
    });

    onCleanup(() => unsubscribe());
  });

  let threadId: string | null = options.threadId ?? null;

  const branch = signal<string>("");

  const getMessages = (value: StateType): Message[] => {
    const messagesKey = options.messagesKey ?? "messages";
    return Array.isArray(value[messagesKey])
      ? (value[messagesKey] as Message[])
      : [];
  };

  const setMessages = (current: StateType, messages: Message[]): StateType => {
    const messagesKey = options.messagesKey ?? "messages";
    return { ...current, [messagesKey]: messages };
  };

  const historyValues = options.initialValues ?? ({} as StateType);

  const historyMessages = getMessages(historyValues);
  const shouldReconstructSubagents =
    options.filterSubagentMessages &&
    !stream.isLoading &&
    historyMessages.length > 0;

  effect(() => {
    const loading = isLoading();
    const hvMessages = getMessages(historyValues);
    const should =
      options.filterSubagentMessages && !loading && hvMessages.length > 0;
    if (should) {
      stream.reconstructSubagents(hvMessages, { skipIfPopulated: true });
    }
  });

  if (shouldReconstructSubagents) {
    stream.reconstructSubagents(historyMessages, { skipIfPopulated: true });
  }

  function switchThread(newThreadId: string | null) {
    if (newThreadId !== threadId) {
      threadId = newThreadId;
      stream.clear();
    }
  }

  function stop() {
    return stream.stop(historyValues, { onStop: options.onStop });
  }

  async function submitDirect(
    values: UpdateType | null | undefined,
    submitOptions?: CustomSubmitOptions<StateType, ConfigurableType>,
  ) {
    const currentThreadId = options.threadId ?? null;
    if (currentThreadId !== threadId) {
      threadId = currentThreadId;
      stream.clear();
    }

    let usableThreadId = threadId ?? submitOptions?.threadId;

    stream.setStreamValues(() => {
      if (submitOptions?.optimisticValues != null) {
        return {
          ...historyValues,
          ...(typeof submitOptions.optimisticValues === "function"
            ? submitOptions.optimisticValues(historyValues)
            : submitOptions.optimisticValues),
        };
      }

      return { ...historyValues };
    });

    await stream.start(
      async (signal: AbortSignal) => {
        if (!usableThreadId) {
          usableThreadId = crypto.randomUUID();
          threadId = usableThreadId;
          options.onThreadId?.(usableThreadId);
        }

        if (!usableThreadId) {
          throw new Error("Failed to obtain valid thread ID.");
        }

        return options.transport.stream({
          input: values,
          context: submitOptions?.context,
          command: submitOptions?.command,
          signal,
          config: {
            ...submitOptions?.config,
            configurable: {
              thread_id: usableThreadId,
              ...submitOptions?.config?.configurable,
            } as unknown as GetConfigurableType<Bag>,
          },
        }) as Promise<
          AsyncGenerator<EventStreamEvent<StateType, UpdateType, CustomType>>
        >;
      },
      {
        getMessages,
        setMessages,

        initialValues: {} as StateType,
        callbacks: options,

        onSuccess: () => undefined,
        onError(error) {
          options.onError?.(error, undefined);
          submitOptions?.onError?.(error, undefined);
        },
      },
    );
  }

  async function submit(
    values: UpdateType | null | undefined,
    submitOptions?: CustomSubmitOptions<StateType, ConfigurableType>,
  ) {
    await submitDirect(values, submitOptions);
  }

  // Browser tools handling
  const handledBrowserTools = new Set<string>();
  let lastThreadId = options.threadId;

  effect(() => {
    const vals = streamValues();

    // Reset dedup set when thread changes
    if (options.threadId !== lastThreadId) {
      lastThreadId = options.threadId;
      handledBrowserTools.clear();
    }

    const { browserTools, onBrowserTool } = options;
    if (!browserTools?.length) return;

    const interrupts = vals?.__interrupt__;
    if (!Array.isArray(interrupts) || interrupts.length === 0) return;

    for (const interrupt of interrupts) {
      if (!isBrowserToolInterrupt(interrupt.value)) continue;

      const interruptId = interrupt.id ?? interrupt.value.toolCall.id ?? "";
      if (handledBrowserTools.has(interruptId)) continue;
      handledBrowserTools.add(interruptId);

      void handleBrowserToolInterrupt(
        interrupt.value,
        browserTools,
        onBrowserTool,
      ).then((result) => {
        void submit(null, {
          command: {
            resume: result.toolCallId
              ? { [result.toolCallId]: result.value }
              : result.value,
          },
        });
      });
    }
  });

  const values = computed(() => streamValues() ?? ({} as StateType));

  function setBranch(value: string) {
    branch.set(value);
  }

  function getMessagesMetadata(
    message: Message<ToolCallType>,
    index?: number,
  ): MessageMetadata<StateType> | undefined {
    const streamMetadata = messageManager.get(message.id)?.metadata;
    if (streamMetadata != null) {
      return {
        messageId: message.id ?? String(index),
        firstSeenState: undefined,
        branch: undefined,
        branchOptions: undefined,
        streamMetadata,
      } as MessageMetadata<StateType>;
    }
    return undefined;
  }

  return {
    values,
    error: streamError,
    isLoading,

    stop,
    submit,
    switchThread,

    branch,
    setBranch,
    getMessagesMetadata,

    queue: {
      entries: signal([]),
      size: signal(0),
      async cancel() {
        return false;
      },
      async clear() {},
    },

    interrupts: computed((): Interrupt<InterruptType>[] => {
      const vals = streamValues();
      if (
        vals != null &&
        "__interrupt__" in vals &&
        Array.isArray(vals.__interrupt__)
      ) {
        const valueInterrupts = vals.__interrupt__;
        if (valueInterrupts.length === 0) return [{ when: "breakpoint" }];
        return valueInterrupts;
      }

      return [];
    }),

    interrupt: computed((): Interrupt<InterruptType> | undefined => {
      return extractInterrupts<InterruptType>(streamValues());
    }),

    messages: computed(() => {
      const vals = streamValues();
      if (!vals) return [];
      return ensureMessageInstances(getMessages(vals));
    }),

    toolCalls: computed(() => {
      const vals = streamValues();
      if (!vals) return [];
      const msgs = getMessages(vals);
      return getToolCallsWithResults<ToolCallType>(msgs);
    }),

    getToolCalls(message: Message<ToolCallType>) {
      const vals = streamValues();
      if (!vals) return [];
      const msgs = getMessages(vals);
      const allToolCalls = getToolCallsWithResults<ToolCallType>(msgs);
      return allToolCalls.filter((tc) => tc.aiMessage.id === message.id);
    },

    get subagents() {
      void subagentVersion();
      return stream.getSubagents();
    },

    get activeSubagents() {
      void subagentVersion();
      return stream.getActiveSubagents();
    },

    getSubagent(toolCallId: string) {
      return stream.getSubagent(toolCallId);
    },

    getSubagentsByType(type: string) {
      return stream.getSubagentsByType(type);
    },

    getSubagentsByMessage(messageId: string) {
      return stream.getSubagentsByMessage(messageId);
    },
  };
}
